Plus minus
primebotio/python-training-camp pull request #8
Opened 2018-10-13 13:56 UTC by leankyr

Ποιο Σωστό Pull request Αυτό?

2018-10-14 14:56 UTC, dimkirt requested changes
- Don't import unused libraries
- Remove the .txt files, either write tests with a framework like pytest or don't upload any test cases
- Finish the problem first and then we will merge it to master
- Assign a reviewer only if you are done or you need advice, if you need advice change the title to WIP: so that the reviewer knows that this PR is Work In Progress

2018-10-14 14:59 UTC, dimkirt commented on leankyr/Easy_Problems/Plus_Minus/plusMinus.py
> +    #plusMinus(arr)
so you didn't finish the problem yet right?

2018-10-18 18:39 UTC, leankyr commented
this is v 1.0 of PlusMinus implementation

2018-10-18 20:04 UTC, leankyr commented
This time I used list comprehensions

2018-10-18 20:45 UTC, dimkirt approved these changes

2018-10-18 20:45 UTC, merged